engines:
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - features/page_objects/**.rb

exclude_paths:
  - features/step_definitions/
  - "**.feature"
  - Gemfile.lock
  - LICENSE
  - "**.md"
