# The standard place to add your features and step_definitions is in a folder
# named 'features' at the root of the project. However if you'd like to name
# this folder something else, you can tell Quke what the new name is here.
# The default is features
# features_folder: 'cukes'

# Normally Capybara expects to be testing an in-process Rack application, but
# we're using it to talk to a remote host. Users of Quke can set what this
# will be by simply setting `app_host`. You can then use it directly using
# Capybara `visit('/Main_Page')` or `visit('/')` rather than having to repeat
# the full url each time
# app_host: 'http://localhost:3000'
app_host: 'https://fra-tst.aws.defra.cloud'
# app_host: 'https://fra-dev.aws.defra.cloud'
# app_host: 'https://fra-pre.aws.defra.cloud'

# Tells Quke which browser to use for testing. Choices are firefox, chrome
# browserstack and phantomjs, with the default being phantomjs
driver: chrome

headless: true

# Add a pause (in seconds) between steps so you can visually track how the
# browser is responding. Only useful if using a non-headless browser. The
# default is 0
pause: 0

# Specify whether Quke should stop all tests once an error occurs. Useful in
# Continuous Integration (CI) environments where a quick Yes/No is preferable to
# a detailed response.
stop_on_error: 1

# Capybara will attempt to find an element for a period of time, rather than
# immediately failing because the element cannot be found. This defaults to 2
# seconds. However if the site you are working with is slow or features
# elements that take some time to load you can increase this default.
max_wait_time: 5

custom:
  accounts:
    SystemUser:
      username: applicant1@example.com
      username2: applicant2@example.com
      password: Abcde12345

  urls:
    # # local
    # front_office: "http://localhost:3000"
    # back_office: "http://localhost:8000"
    # # dev
    # front_office: "https://fra-dev.aws.defra.cloud"
    # back_office: "https://fra-admin-dev.aws.defra.cloud"
    # test
    front_office: "https://fra-tst.aws.defra.cloud"
    back_office: "https://fra-admin-tst.aws.defra.cloud"
    # # preprod
    # front_office: "https://fra-pre.aws.defra.cloud"
    # back_office: "https://fra-admin-pre.aws.defra.cloud"
