AllCops:
  # Cop names are not displayed in offense messages by default. We find it
  # useful to include this information so we can use it to investigate what the
  # fix may be.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Again we
  # find it useful to go straight to the documentation for a rule when
  # investigating what the fix may be.
  DisplayStyleGuide: true

# When using Ruby >= 2.3, Rubocop wants to add a comment to the top of *.rb
# to aid migration to frozen literals in Ruby 3.0. We are not interested in
# modifying every file at this point, so this cop is disabled for now.
Style/FrozenStringLiteralComment:
  Enabled: false

# As long as the team commit to using well named classes it should not be
# necessary to add top-level class documentation.
Style/Documentation:
  Enabled: false

# We believe it looks cluttered/ugly not having the ability to add whitespace
# between for example the class declaration and first method.
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# There are no relative performance improvements using '' over "", therefore we
# believe there is more value in using "" for all strings irrespective of
# whether string interpolation is used
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We believe the default of 10 lines for a method length is too restrictive and
# often quickly hit just because we need to specify the namesspace, class and
# method before then doing something with it.
Metrics/MethodLength:
  Max: 30

# We believe the default 80 characters is too restrictive and that lines can
# still be readable and maintainable when no more than 120 characters. This also
# allows us to maximise our screen space.
Metrics/LineLength:
  Max: 120

# We felt as a team that the default size of 15 was too low, and blocked what to
# us are sound methods which would not add any value if broken up. In this
# project we've agreed to up this to 30.
Metrics/AbcSize:
  Max: 30

# We felt as a team that the default size of 6 was too low, and blocked what to
# us are sound methods which would not add any value if broken up. In this
# project we've agreed to up this to 7.
Metrics/CyclomaticComplexity:
  Max: 7
