inherit_gem:
  defra_ruby_style:
    - default.yml

# Our steps are not traditional code blocks and as such rules about there
# length we don't feel apply. They are a step in a feature and as we want
# the features to be meaningful, the last thing we want to do is start breaking
# them up for the sake of this rubocop rule.
Metrics/BlockLength:
  Exclude:
    - "features/step_definitions/**/*"
