sudo: false
language: ruby
rvm:
  - 2.4.2

# Travis CI clones repositories to a depth of 50 commits, which is only really
# useful if you are performing git operations.
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 3

# enable Bundler caching
# https://docs.travis-ci.com/user/languages/ruby#Caching-Bundler
cache: bundler

# Using the ability to customise the Travis build to check for 'temporary' tags
# i.e. tags often used when working on a feature/scenario but which we don't
# want appearing in the final commit to master
before_script:
  - echo "Checking for use of temporary tags in .feature files"
  # Reworking of http://stackoverflow.com/a/30495279/6117745
  # If grep returns 0 (match found), test 0 -eq 1 will return 1.
  # If grep returns 1 (no match found), test 1 -eq 1 will return 0.
  # If grep returns 2 (error), test 2 -eq 1 will return 1.
  - grep -r --include="*.feature" "@wip\|@focus" features/; test $? -eq 1
